name: draft
description: Immer, but for dart. Convert between immutable and mutable objects.
version: 0.0.9
repository: https://github.com/josiahsrc/draft

environment:
  sdk: ^3.6.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
