targets:
  $default:
    builders:
      draft_builder:
        enabled: true
        generate_for:
          exclude:
            - test
            - example
          include:
            - test/integration/*
            - test/integration/**/*
      source_gen|combining_builder:
        options:
          ignore_for_file:
            - "type=lint"

builders:
  draft_builder:
    import: "package:draft_builder/draft_builder.dart"
    builder_factories: ["draftBuilder"]
    build_extensions: { ".dart": [".draft.dart"] }
    auto_apply: dependents
    build_to: source
